# Sets up a github clone on the main host
--- 
- block:
  - name: Check if repository already exists
    stat:
      path: ~/Expense_Tracker
    register: et_repo_exists
  
  - name: Add git to known ssh hosts
    shell: 'ssh-keyscan github.com >> ~/.ssh/known_hosts'

  - name: Clone the Expense_Tracker repo
    shell: 'source /home/provision-central/.profile && git clone git@github.com:steven85048/Expense_Tracker.git'
    args:
      chdir: /home/provision-central/
      executable: /bin/bash
    when: et_repo_exists.stat.exists == False

  become: yes
  become_user: provision-central