---
- name: apt install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - python
      - python-pip
      - ansible
      - unzip

- name: install boto/botocore for s3 through pip
  pip:
    name: "{{ item }}"
  loop:
    - botocore
    - boto
    - boto3

- name: Extract zipped file into searched executables
  unarchive: 
    src: https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes