---
- block:
  - name: apt install packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - python
        - python-pip
        - unzip

  - name: Install latest version of ansible
    shell: |
      sudo apt-add-repository ppa:ansible/ansible
      sudo apt update
      sudo apt install ansible 
    EOF

  - name: install boto/botocore for s3 through pip
    pip:
      name: "{{ item }}"
    loop:
      - botocore
      - boto
      - boto3

  - name: Extract terraform zipped file into searched executables
    unarchive: 
      src: https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes 
  
  - name: Download terragrunt
    get_url: 
      url: https://github.com/gruntwork-io/terragrunt/releases/download/v0.20.5/terragrunt_linux_amd64
      dest: /usr/local/bin/terragrunt
      mode: '0770'

  become: yes