---
- block: 
  - name: "Create {{ default_user }} user"
    user: 
      name: "{{ default_user }}"
      shell: /bin/bash
      groups:
        - sudo
    register: "{{ default_user }}"
  
  - name: Set the initial authorized key to the machine aws public key
    authorized_key:
      user: "{{ default_user }}"
      state: present
      key: "{{ lookup('file', lookup('env', 'HOME') + default_user_key ) }}'"

  - name: Force login through public key
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication.*yes'
      line: 'PasswordAuthentication=no'
    notify: restart_sshd

  become: yes
  become_user: root