---
- block:
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: 
      update_cache: yes 
      name: "{{ item }}"
      state: latest
    loop:
      - docker-ce 
      - docker-compose

  - name: Install Docker Module for Python
    pip:
      name: "{{ item }}"
    loop:
      - docker
      - docker-compose

  - name: Ensure docker group exists
    group:
      name: docker
      state: present

  - name: Add {{ default_user }} to docker group
    user: 
      name: "{{ default_user }}"
      groups: docker
      append: yes

  - name: Update ~/.docker/config.json
    copy:
      src: config.json
      dest: "/home/{{ default_user }}/.docker/config.json"
      owner: "{{ default_user }}"
      group: "{{ default_user }}"
      mode: '0644'

  become: yes
  become_user: root
