---
- name: "Clone the {{ default_repo }} repo with ssh agent"
  include_role: 
    name: utility_roles/git-clone-with-agent
  vars:
    repo_ssh_url: "git@github.com:steven85048/{{ default_repo }}.git"
    repo_name: "{{ default_repo }}"
    repo_owner: "{{ default_user }}"