---
# Note that this module assumes that ssh forwarding is set up from the bastion host

- name: Ensure SSH Forwarding Agent is running
  command: ssh-add -l

- name: Check if repository already exists
  stat:
    path: /home/provision/Expense_Tracker
  register: et_repo
  become: yes
  become_user: root

- block:
  # IMPORTANT: Since we are using agent forwarding, changing the user loses the ssh-agent!!!
  # Do not want to use become in this case
  - name: Clone the Expense_Tracker repo
    git:
      repo: 'git@github.com:steven85048/Expense_Tracker.git'
      dest: /home/ubuntu/Expense_Tracker
      clone: yes
      accept_hostkey: yes

  - name: Move repo to provision user
    command: mv /home/ubuntu/Expense_Tracker /home/provision/Expense_Tracker
    become: yes
    become_user: root

  - name: Change the owner of the repository
    command: sudo chown provision:provision . -R
    become: yes
    become_user: root
    args:
      chdir: /home/provision/Expense_Tracker/

  when:  et_repo.stat.exists == false