---
# Note that this module assumes that ssh forwarding is set up from the bastion host

- name: Clone the Expense_Tracker repo
  git:
    repo: 'git@github.com:steven85048/Expense_Tracker.git'
    dest: /home/provision/Expense_Tracker
    clone: yes
    accept_hostkey: yes
  become_user: root
  become: yes
