---
- block: 
  - name: Install aptitude using apt
    apt: 
      name: aptitude 
      state: latest 
      update_cache: yes 
      force_apt_get: yes

  - name: Install required system packages
    apt: 
      name: "{{ item }}" 
      state: latest 
      update_cache: yes
    loop: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip 
      - virtualenv
      - python3-setuptools

  become: yes
  become_user: root