---
- block: 
  - name: Create provision user
    user: 
      name: provision
      password: "{{ lookup('file', '/home/provision-central/provision-password') | password_hash('sha512') }}"
      shell: /bin/bash
      update_password: on_create
    register: provision
    
  - name: Force provision change password
    shell: chage -d 0 provision
    register: provision.changed

  - name: Add no-password sudo permissions for new user
    copy:
      dest: "/etc/sudoers.d/provision"
      content: "provision\tALL=(ALL)\tNOPASSWD: ALL"
  
  become: yes
  become_user: root