---
- block: 
  - name: Create provision user
    user: 
      name: provision
      password: "{{ 'test_pass' | password_hash('sha512') }}"
      shell: /bin/bash
      update_password: on_create
      groups:
        - sudo
    register: provision
    
  - name: Force provision change password
    shell: chage -d 0 provision
    register: provision.changed
  
  become: yes
  become_user: root