---
# May become a submodule of the main repo later, so this may be removed eventually
- name: "Clone the {{ service_repo }} repo with ssh agent"
  include_role: 
    name: utility_roles/git-clone-with-agent
  vars:
    repo_ssh_url: "git@github.com:steven85048/{{ service_repo }}.git"
    repo_name: "{{ service_repo }}"
    repo_owner: "{{ default_user }}"