---
- name: Check if repository already exists
  stat:
    path: /home/provision/Networks_Client_Server
  register: ncs_repo
  become: yes
  become_user: root

# IMPORTANT: Since we are using agent forwarding, changing the user loses the ssh-agent!!!
# Do not want to use become in this case
- name: Clone the Expense_Tracker repo
  git:
    repo: 'git@github.com:steven85048/Networks_Client_Server.git'
    dest: /home/ubuntu/Expense_Tracker
    clone: yes
    accept_hostkey: yes
  when: ncs_repo.stat.exists == false

- name: Move repo to provision user
  command: mv /home/ubuntu/Networks_Client_Server /home/provision/Networks_Client_Server
  become: yes
  become_user: root
  when: ncs_repo.stat.exists == false
