---
- name: install python and ansible
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python
      - ansible

- name: install boto/botocore for s3 through pip
  pip:
    name: "{{ item }}"
  loop:
    - botocore
    - boto
    - boto3