---
- name: Create secrets directory under the root user
  file:
    path: /home/root/user-passwords
    state: directory
    mode: '0700'

- name: Get the provision-central-password from s3
  aws_s3:
    bucket: expense-tracker-secrets
    object: /host-secrets/{{ item }}
    dest: /home/root/user-passwords/{{ item }}
    mode: get
  loop:
    - "provision-central-password"
    - "provision-password"

- name: Add a new provision-central user
  user:
    name=provision-central
    password="{{ lookup('file', '/home/root/user-passwords/provision-central-password') }}"

- name: Add no-password sudo permissions for new user
  copy:
    dest: "/etc/sudoers.d/provision"
    content: "provision\tALL=(ALL)\tNOPASSWD: ALL"