# This playbook installs the deploy key private key for this host to allow for automatic pulls of the repository
# Must be run after provision-central user setup
---
- block:
  - name: Check expense-tracker-id_rsa exists
    stat:
      path: ~/.ssh/expense-tracker-id_rsa
    register: et_id_rsa_exists

  - name: Install the default SSH key for accessing slave machines
    shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/expense-tracker-id_rsa -q -N ""
    when: et_id_rsa_exists.stat.exists == False

  - name: Check expense-tracker-github-id_rsa exists
    stat:
      path: ~/.ssh/expense-tracker-github-id_rsa
    register: et_github_id_rsa_exists

  - name: Install the github private key from S3
    aws_s3:
      bucket: expense-tracker-secrets
      object: /host-secrets/expense-tracker-github-id_rsa
      dest: ~/.ssh/expense-tracker-github-id_rsa
      mode: get
    when: et_github_id_rsa_exists.stat.exists == False

  - name: Start the ssh-agent daemon
    shell: 'eval $(ssh-agent)'

  - name: Add the ssh keys to the ssh-agent
    shell: 'ssh-add {{ item }}'
    loop:
      - ~/.ssh/expense-tracker-id_rsa
      - ~/.ssh/expense-tracker-github-id_rsa

  become: yes
  become_user: provision-central
