# This playbook installs the deploy key private key for this host to allow for automatic pulls of the repository
# Must be run after provision-central user setup
---
- block:
  - name: Check expense-tracker-id_rsa exists
    stat:
      path: ~/.ssh/expense-tracker-id_rsa
    register: et_id_rsa_exists

  - name: Install the default SSH key for accessing slave machines
    shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/expense-tracker-id_rsa -q -N ""
    when: et_id_rsa_exists.stat.exists == False

  - name: Check expense-tracker-github-id_rsa exists
    stat:
      path: ~/.ssh/expense-tracker-github-id_rsa
    register: et_github_id_rsa_exists

  - name: Install the github private key from S3
    aws_s3:
      bucket: expense-tracker-secrets
      object: /host-secrets/expense-tracker-github-id_rsa
      dest: ~/.ssh/expense-tracker-github-id_rsa
      mode: get
    when: et_github_id_rsa_exists.stat.exists == False

  - name: Change permissions of all .ssh files
    file:
      path: "{{ item.src }}"
      mode: 0600
    with_filetree: /home/provision-central/.ssh

  # Gets all processes with provision-central and ssh-agent EXCEPT for the grep process searching this
  # In addition, modify the user column to have more characters
  - name: Check if ssh-agent already running under provision-central user
    shell: 'ps axo user:20,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,comm | grep "provision-central.*ssh-agent" | grep -v "grep"'
    register: ssh_agent_running
    failed_when: "ssh_agent_running.rc == 2"
    check_mode: no
    changed_when: false

  - name: Print the pgrep output
    debug:
      msg: "The output of pgrep is: {{ ssh_agent_running }}"

  - block:
    - name: Start the ssh-agent daemon when not running 
      shell: 'ssh-agent | head -n 2'
      register: ssh_agent_environment_set

    - name: Delete ssh-agent-block
      blockinfile:
        marker: "## {mark} added by ansible (configuration ssh-agent)"
        dest: ~/.profile
        block: ""

    - name: Update bashrc with ssh-agent environment variable set
      blockinfile:
        marker: '## {mark} added by ansible (configuration ssh-agent)'
        dest: ~/.profile
        block: |
          {{ ssh_agent_environment_set.stdout }}

    when: ssh_agent_running.stdout == ""

  # Note that if ssh-agent was started without setting the .bashrc, this command will fail
  # In this case, loosen the above when when condition so that the block is run, and stop any
  # previously running ssh-agent. 
  - name: Add the ssh keys to the ssh-agent
    shell: 'source /home/provision-central/.profile && ssh-add {{ item }}'
    loop:
      - ~/.ssh/expense-tracker-id_rsa
      - ~/.ssh/expense-tracker-github-id_rsa

  become: yes
  become_user: provision-central
