# Sets up the docker containers necessary for the server configuration
# Note that generally the web server and database are generally on different hosts for reasons such as horizontal scaling, but
# we keep it on one host here for simplicity for now
version: "2"
services:  
  postgresql:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  server:
    container_name: networks_messaging_server
    image: 003195358776.dkr.ecr.us-east-2.amazonaws.com/expense_tracker_ecr:latest
    ports:
      - "5006:5006"