---
- name: Installs the necessary api keys from s3
  aws_s3:
    bucket: expense-tracker-secrets
    object: "{{item}}"
    dest: "/etc/secrets/{{item}}"
    mode: get
  loop:
    - plaid-client-id
    - plaid-public-key
    - plaid-secret-{{plaid_dsp}}  
