---
block: 
  - name: Create secrets directory under etc
    file:
      path: /etc/secrets
      state: directory
      mode: '0770'
      group: provision

  - name: Installs the necessary api keys from s3
    aws_s3:
      bucket: expense-tracker-secrets
      object: "/api_keys/{{item}}"
      dest: "/etc/secrets/{{item}}"
      mode: get
    loop:
      - plaid-client-id
      - plaid-public-key
      - plaid-secret-{{plaid_dsp}}  
  - become: yes
